---
version: '3.4'
services:
  db:
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports: ["5432:5432"]
  app: &app-common
    build: "."
    command: bin/wait-for-it.sh db:5432 -- passenger start -p 3000
    environment: &app-environment
      DATABASE_URL: postgresql://postgres:postgrespassword@db
      REDIS_URL: redis://redis:6379
      SIDEKIQ_REDIS_URL: redis://redis:6379
      LOG_LEVEL: debug
      SKYLIGHT_ENABLED: false
    links:
    - db
    - redis
    volumes: [".:/app"]
    ports: ["3000:3000"]
  redis:
    image: redis:5.0.3
    ports: ["6379:6379"]
  app-poll-room-queue:
    <<: *app-common
    environment:
      <<: *app-environment
      LOG_LEVEL: info
    command: bin/wait-for-it.sh db:5432 -- bin/wait-for-it.sh redis:6379 -- rake room:poll_queue
    ports: []
  app-sidekiq-workers:
    <<: *app-common
    command: bin/wait-for-it.sh db:5432 -- bin/wait-for-it.sh redis:6379 -- bundle exec sidekiq
    ports: []
    environment:
      <<: *app-environment
      DB_POOL: 1
      SIDEKIQ_CONCURRENCY: 5
