---
version: '3.4'
services:
  proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  acme:
    image: nginxproxy/acme-companion
    depends_on:
      - proxy
    volumes:
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro \
    environment:
      DEFAULT_EMAIL: truman@gobetweenlab.com
  db:
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports: ["5432:5432"]
  app: &app-common
    build: "."
    command: bin/wait-for-it.sh db:5432 -- passenger start -p 3000 --nginx-config-template nginx.conf.erb
    environment: &app-environment
      DATABASE_URL: postgresql://postgres:postgrespassword@db
      REDIS_URL: redis://redis:6379
      SIDEKIQ_REDIS_URL: redis://redis:6379
      LOG_LEVEL: debug
      SKYLIGHT_ENABLED: "false"
      LETSENCRYPT_HOST: localhost
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 3000
    links:
    - db
    - redis
    volumes: [".:/app"]
    ports: ["3000:3000"]
  redis:
    image: redis:5.0.3
    ports: ["6379:6379"]
  app-poll-room-queue:
    <<: *app-common
    environment:
      <<: *app-environment
      LOG_LEVEL: info
    command: bin/wait-for-it.sh db:5432 -- bin/wait-for-it.sh redis:6379 -- rake room:poll_queue
    ports: []
  app-sidekiq-workers:
    <<: *app-common
    command: bin/wait-for-it.sh db:5432 -- bin/wait-for-it.sh redis:6379 -- bundle exec sidekiq
    ports: []
    environment:
      <<: *app-environment
      DB_POOL: 1
      SIDEKIQ_CONCURRENCY: 5
