development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: musicbox-api_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: musicbox-api_production
