:verbose: false
:concurrency: 5
:timeout: 8
:queues:
  - [queue_management, 1]
  - [broadcast_message, 1]
  - [broadcast_now_playing, 1]
  - [broadcast_playlist, 1]
  - [broadcast_users, 1]
  - [email_invitations, 1]
